Repository DDrawry/ddrawry-FE, pull requests merged in 2024-10, with the labels that each got.

#52 Chore: apiRoutes 및 proxy 설정
  src/api/apiRoutes.ts
  src/api/fetcher.ts
  vite.config.ts
Labels: 세팅

#54 Setting: husky 세팅 & 타입 체크
  .husky/pre-commit
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/diary/image/ImageCreationPanel.stories.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/iconComponents/mood/MoodList.stories.tsx
  src/components/iconComponents/weather/WeatherList.stories.tsx
  src/components/search/Search.stories.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchIcon.tsx
  src/pages/ErrorPage/page/index.tsx
Labels: 세팅

#58 Style: 일기 수정/작성 페이지 스타일 수정
  src/components/buttons/SmallButton.tsx
  src/components/diary/Diary.tsx
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/diary/image/ImagesHistoryButton.tsx
  src/pages/WriteDiaryPage/components/WriteDiaryButtonSection.tsx
  src/pages/WriteDiaryPage/page/index.tsx
Labels: fix, 스타일

#63 hotfix: 좋아요한 일기 페이지 UI 수정
  src/api/liked/useLikeStatus.ts
  src/components/iconComponents/LikeIcon.tsx
  src/pages/LikedPage/page/index.tsx
Labels: 페이지, 기능, 핫픽스

#65 Feat: 유저 관련 api 연동 작업
  .husky/pre-commit
  src/api/fetcher.ts
  src/api/users/useChangeNickname.ts
  src/api/users/useChangeUserSetting.ts
  src/api/users/useDeleteAccount.ts
  src/api/users/useLogout.ts
  src/components/buttons/Button.stories.tsx
  src/components/diary/image/ImageCreationPanel.stories.tsx
  src/components/modals/ChangeNameModal.tsx
  src/components/modals/ProfileModal.tsx
  src/store/DarkModeContext.tsx
Labels: 기능

#67 Feat: 임시저장 API연결
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/diary/useTempDiary.ts
  src/components/diary/list/DiaryItem.tsx
  src/pages/DiaryPage/page/index.tsx
  src/pages/LikedPage/page/index.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/WriteDiaryPage/components/TempSaveModal.tsx
  src/pages/WriteDiaryPage/components/WriteDiaryButtonSection.tsx
  src/pages/WriteDiaryPage/page/index.tsx
Labels: 페이지, 기능

#68 Feat: 로그인 로직 작업
  src/api/apiRoutes.ts
  src/api/fetcher.ts
  src/components/diary/Diary.stories.tsx
  src/components/diary/image/ImageCreationPanel.stories.tsx
  src/components/iconComponents/mood/MoodList.stories.tsx
  src/components/iconComponents/weather/WeatherList.stories.tsx
  src/constants/domain.ts
  src/pages/LoginPage/page/index.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 페이지, 기능

#70 hotfix: vercel.json에 rewrite 추가
  vercel.json
Labels: 페이지, 기능

#71 Deploy: vercel.json에 rewrite 추가해서 다시 배포
  vercel.json
Labels: 배포

#74 Feat/#55: 로그인 페이지 API 작업
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/fetcher.ts
  src/api/users/useLogin.ts
  src/constants/login.ts
  src/pages/LikedPage/page/index.tsx
  src/pages/LoginPage/loginHandler/oauthHandler.tsx
  src/pages/LoginPage/page/index.tsx
  vite.config.ts
Labels: 페이지, 기능
