Repository DDrawry/ddrawry-FE, pull requests merged in 2024-08, with the labels that each got.

#2 Chore: 개발 환경 세팅
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/assets/fonts/CookieRun Regular.otf
  src/assets/fonts/CookieRun Regular.ttf
  src/assets/fonts/CookieRun Regular.woff2
  src/assets/fonts/CookieRun-Regular.woff
  src/index.css
  src/pages/DiaryPage/page/index.tsx
  tailwind.config.js
Labels: documentation

#4 Add: PR 템플릿 생성
  .github/pull_request_template.md
Labels: documentation

#5 Style: 아이콘이 없는 DefaultHeader 컴포넌트 작업 완료
  .gitignore
  .storybook/preview.ts
  chromatic.config.json
  src/App.css
  src/components/header/DefaultHeader.tsx
  src/components/header/Header.stories.tsx
  tailwind.config.js
Labels: 컴포넌트, 스타일

#8 Style: 아이콘이 없는 DefaultHeader 컴포넌트 작업 완료
  .gitignore
  .storybook/preview.ts
  chromatic.config.json
  src/App.css
  src/components/header/DefaultHeader.tsx
  src/components/header/Header.stories.tsx
  tailwind.config.js
Labels: 컴포넌트, 스타일

#10 Style/#7
  src/components/header/HasProfileHeader.tsx
  src/components/header/Header.stories.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/header/HeaderWithProfile.tsx
  src/components/iconComponents/LikeIcon.tsx
  src/components/iconComponents/ProfileIcon.tsx
Labels: 컴포넌트, 스타일

#13 Style: DiaryItem 컴포넌트 완료
  package.json
  pnpm-lock.yaml
  src/assets/images/diaryItem-logo.png
  src/components/default/DefaultDiaryLogo.tsx
  src/components/diary/DiaryItem.tsx
  src/components/diary/DiaryList.stories.tsx
  src/components/diary/DiaryList.tsx
  src/index.css
  src/utils/getDate.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 컴포넌트, 스타일

#15 Style: 버튼 공통 컴포넌트 작업 완료
  package.json
  pnpm-lock.yaml
  src/assets/images/diaryItem-logo.png
  src/assets/svgs/KakaoIcon.svg
  src/components/buttons/BigButton.tsx
  src/components/buttons/BlueButton.tsx
  src/components/buttons/Button.stories.tsx
  src/components/buttons/GreenButton.tsx
  src/components/buttons/KakaoButton.tsx
  src/components/buttons/ModalButton.tsx
  src/components/buttons/SmallButton.tsx
  src/components/buttons/ToggleButton.tsx
  src/components/buttons/YellowButton.tsx
  src/components/default/DefaultDiaryLogo.tsx
  src/components/diary/DiaryItem.tsx
  src/components/diary/DiaryList.stories.tsx
  src/components/diary/DiaryList.tsx
  src/components/header/DefaultHeader.tsx
  src/components/header/HasLikeHeader.tsx
  src/components/header/HasProfileHeader.tsx
  src/components/header/Header.stories.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/header/HeaderWithProfile.tsx
  src/components/iconComponents/ImageIcon.tsx
  src/components/iconComponents/LikeIcon.tsx
  src/components/iconComponents/LinkIcon.tsx
  src/components/iconComponents/PaintIcon.tsx
  src/components/iconComponents/ProfileIcon.tsx
  src/index.css
  src/pages/LoginPage/components/KaKaoLoginButton.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/utils/getDate.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: fix, 컴포넌트, 스타일
