Repository DDrawry/ddrawry-FE, pull requests merged in 2024-12, with the labels that each got.

#107 Feat: 페이지 로딩 핸들링 및 코드 스플리팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/diary/useDeleteDiary.ts
  src/api/liked/useLikeStatus.ts
  src/api/users/useChangeNickname.ts
  src/api/users/useDeleteAccount.ts
  src/api/users/useLogout.ts
  src/components/diary/Diary.tsx
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/header/HeaderWithProfile.tsx
  src/components/loading/LoadingSpinner.tsx
  src/components/modals/ChangeNameModal.tsx
  src/components/modals/ImageEditModal.tsx
  src/components/modals/InformationModal.tsx
  src/components/modals/Modal.stories.tsx
  src/components/modals/ModalLayout.tsx
  src/components/modals/ProfileModal.tsx
  src/index.css
  src/pages/DiaryPage/components/DiaryButtonSection.tsx
  src/pages/DiaryPage/page/index.tsx
  src/pages/LikedPage/page/index.tsx
  src/pages/LoginPage/loginHandler/oauthHandler.tsx
  src/pages/MainPage/components/calender/CalenderItem.tsx
  src/pages/MainPage/components/calender/CalenderView.tsx
  src/pages/SearchPage/page/index.tsx
  src/pages/SharedPage/index.tsx
  src/pages/WriteDiaryPage/components/WriteDiaryButtonSection.tsx
  src/pages/WriteDiaryPage/page/index.tsx
  src/types/modalType.ts
  src/utils/ScrollTo.ts
  stats.html
  vite.config.ts
Labels: 성능개선, 기능

#109 feat: ImageCreationPanel 그림그릴때 로딩 애니메이션 처리
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/loading/LoadingAnimation.tsx
  src/components/loading/LoadingWord1.tsx
  src/components/loading/LoadingWord2.tsx
  src/components/loading/LoadingWord3.tsx
  tailwind.config.js
Labels: 컴포넌트, 기능

#111 Style/#110
  src/assets/svgs/CircleXIcon.svg
  src/components/buttons/BigButton.tsx
  src/components/buttons/ModalButton.tsx
  src/components/buttons/SmallButton.tsx
  src/components/buttons/ToggleButton.tsx
  src/components/default/DefaultDiaryLogo.tsx
  src/components/diary/Diary.tsx
  src/components/diary/DisplaySection.tsx
  src/components/diary/InputSection.tsx
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/diary/list/DiaryItem.tsx
  src/components/diary/list/DiaryList.tsx
  src/components/empty/EmptyState.tsx
  src/components/header/DefaultHeader.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/header/HeaderWithProfile.tsx
  src/components/iconComponents/CircleXIcon.tsx
  src/components/iconComponents/LikeIcon.tsx
  src/components/iconComponents/ProfileIcon.tsx
  src/components/iconComponents/XIcon.tsx
  src/components/iconComponents/mood/MoodList.tsx
  src/components/iconComponents/mood/moodItem/AngryIcon.tsx
  src/components/iconComponents/mood/moodItem/ExcitedIcon.tsx
  src/components/iconComponents/mood/moodItem/HappyIcon.tsx
  src/components/iconComponents/mood/moodItem/MediocreIcon.tsx
  src/components/iconComponents/mood/moodItem/SadIcon.tsx
  src/components/iconComponents/mood/moodItem/SmileIcon.tsx
  src/components/iconComponents/weather/weatherItem/CloudyIcon.tsx
  src/components/iconComponents/weather/weatherItem/RainyIcon.tsx
  src/components/iconComponents/weather/weatherItem/SnowyIcon.tsx
  src/components/iconComponents/weather/weatherItem/SunnyIcon.tsx
  src/components/iconComponents/weather/weatherItem/ThunderStormIcon.tsx
  src/components/iconComponents/weather/weatherItem/WindyIcon.tsx
  src/components/modals/ChangeNameModal.tsx
  src/components/modals/DefaultModal.tsx
  src/components/modals/ImageEditModal.tsx
  src/components/modals/InformationModal.tsx
  src/components/modals/ProfileModal.tsx
  src/components/modals/swiperStyle.css
  src/components/search/SearchBar.tsx
  src/components/search/SearchIcon.tsx
  src/components/search/SearchInput.tsx
  src/hooks/useDarkMode.ts
  src/index.css
  src/pages/DiaryPage/components/DiaryButtonSection.tsx
  src/pages/LikedPage/page/index.tsx
  src/pages/MainPage/components/DateManipulationBar.tsx
  src/pages/MainPage/components/calender/Calender.tsx
  src/pages/MainPage/components/calender/CalenderView.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/SearchPage/components/SearchDiaryView.tsx
  src/pages/SearchPage/page/index.tsx
  src/pages/SharedPage/index.tsx
  src/pages/WriteDiaryPage/components/WriteDiaryButtonSection.tsx
  stats.html
  tailwind.config.js
Labels: 페이지, 스타일

#112 fix: 스타일 오류 수정
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/modals/DefaultModal.tsx
Labels: fix, 핫픽스

#122 Hotfix: QA수정사항
  src/components/diary/Diary.tsx
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/iconComponents/mood/MoodList.tsx
  src/components/iconComponents/weather/WeatherList.tsx
  src/components/modals/ImageEditModal.tsx
  src/main.tsx
  src/pages/MainPage/components/calender/Calender.tsx
  src/pages/MainPage/components/calender/CalenderItem.tsx
  src/pages/WriteDiaryPage/components/TempSaveModal.tsx
  src/pages/WriteDiaryPage/components/WriteDiaryButtonSection.tsx
  src/pages/WriteDiaryPage/page/index.tsx
  src/store/DarkModeContext.tsx
  src/types/WriteDiaryTypes.ts
Labels: fix, 핫픽스

#124 Hotfix: 링크 공유기능 카카오 공유기능으로 수정
  index.html
  src/components/buttons/ModalButton.tsx
  src/pages/DiaryPage/components/DiaryButtonSection.tsx
  src/store/useKakaoShare.ts
  src/types/KakaoType.d.ts
Labels: 기능, 핫픽스

#127 hotfix: 빌드 오류 수정
  src/assets/fonts/CookieRun-Regular.otf
  src/assets/fonts/CookieRun-Regular.ttf
  src/assets/fonts/CookieRun-Regular.woff2
  src/components/modals/Modal.stories.tsx
  stats.html
Labels: 핫픽스

#140 hotfix: 에러 컴포넌트 레이아웃 수정
  src/pages/ErrorPage/components/DefaultErrorComponent.tsx
  src/pages/ErrorPage/errors/GenericError.tsx
  src/utils/ErrorBoundary.tsx
Labels: 기능, 핫픽스

#144 Feat: 홈 화면에 InformationModal 추가
  package.json
  pnpm-lock.yaml
  src/components/modals/InformationModal.tsx
  src/pages/MainPage/page/index.tsx
Labels: 페이지, 기능
