Repository DDrawry/ddrawry-FE, pull requests merged in 2024-09, with the labels that each got.

#17 style: 날짜 관련 컴포넌트 생성
  src/assets/images/calenderItem-logo.png
  src/assets/svgs/KakaoIcon.svg
  src/assets/svgs/LogoImage.svg
  src/assets/svgs/LogoText.svg
  src/components/buttons/BigButton.tsx
  src/components/buttons/BlueButton.tsx
  src/components/buttons/Button.stories.tsx
  src/components/buttons/GreenButton.tsx
  src/components/buttons/KakaoButton.tsx
  src/components/buttons/ModalButton.tsx
  src/components/buttons/SmallButton.tsx
  src/components/buttons/ToggleButton.tsx
  src/components/buttons/YellowButton.tsx
  src/components/calender/Calender.tsx
  src/components/calender/CalenderItem.tsx
  src/components/diary/DiaryItem.tsx
  src/components/header/DefaultHeader.tsx
  src/components/header/Header.stories.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/header/HeaderWithProfile.tsx
  src/components/iconComponents/ImageIcon.tsx
  src/components/iconComponents/LinkIcon.tsx
  src/components/iconComponents/PaintIcon.tsx
  src/hooks/useDateControl.ts
  src/index.css
  src/pages/LoginPage/components/KaKaoLoginButton.tsx
  src/pages/MainPage/components/DateManipulationBar.tsx
  src/pages/MainPage/components/calender/Calender.stories.tsx
  src/pages/MainPage/components/calender/Calender.tsx
  src/pages/MainPage/components/calender/CalenderItem.tsx
  src/pages/MainPage/components/calender/CalenderView.tsx
  src/pages/MainPage/components/icons/LeftArrowIcon.tsx
  src/pages/MainPage/components/icons/Like.tsx
  src/pages/MainPage/components/icons/RightArrowIcon.tsx
  src/types/diaryTypes.ts
  src/utils/getDate.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 컴포넌트, 기능, 스타일

#21 style: SearchIcon, SearchInput, SearchBar 컴포넌트 스타일 작업 완료
  src/components/search/Search.stories.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchIcon.tsx
  src/components/search/SearchInput.tsx
Labels: 컴포넌트, 스타일

#19 Hotfix : 캘린더 컴포넌트 스타일 오류 수정 및 해당 월이 아닌 경우의 날짜에 대한 스타일 지정
  package.json
  pnpm-lock.yaml
  src/pages/MainPage/components/calender/Calender.tsx
  src/pages/MainPage/components/calender/CalenderItem.tsx
Labels: 컴포넌트, 핫픽스

#23 stlye: ImageCreationPanel 컴포넌트 생성 완료
  src/components/buttons/ModalButton.tsx
  src/components/iconComponents/ImageIcon.tsx
  src/pages/DiaryPage/components/ImageCreationPanel.stories.tsx
  src/pages/DiaryPage/components/ImageCreationPanel.tsx
  src/pages/DiaryPage/components/ImagesHistoryButton.tsx
Labels: 컴포넌트, 스타일

#24 Style: 모달 공통 컴포넌트 퍼블리싱 작업 완료
  package.json
  pnpm-lock.yaml
  src/assets/images/logoTextOnly.png
  src/assets/svgs/CircleXIcon.svg
  src/assets/svgs/XIcon.svg
  src/components/buttons/ModalButton.tsx
  src/components/iconComponents/CircleXIcon.tsx
  src/components/iconComponents/XIcon.tsx
  src/components/modals/ChangeNameModal.tsx
  src/components/modals/DefaultModal.tsx
  src/components/modals/EmptyImage.tsx
  src/components/modals/ImageEditModal.tsx
  src/components/modals/Modal.stories.tsx
  src/components/modals/ModalLayout.tsx
  src/components/modals/ProfileModal.tsx
  src/components/modals/RegenerateModal.tsx
  src/components/modals/swiperStyle.css
  src/hooks/useDarkMode.ts
  src/main.tsx
  src/store/DarkModeContext.tsx
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
Labels: 세팅, 컴포넌트, 스타일, 핫픽스

#26 Style: 날씨에 대한 각 Icon 컴포넌트와 Icon들을 일렬로 정렬한 weatherList 컴포넌트 퍼블리싱 작업 완료
  src/assets/svgs/Cloudy.svg
  src/assets/svgs/Rainy.svg
  src/assets/svgs/Snowy.svg
  src/assets/svgs/Sunny.svg
  src/assets/svgs/Thunder.svg
  src/assets/svgs/Windy.svg
  src/components/iconComponents/weather/WeatherList.stories.tsx
  src/components/iconComponents/weather/WeatherList.tsx
  src/components/iconComponents/weather/weatherItem/CloudyIcon.tsx
  src/components/iconComponents/weather/weatherItem/RainyIcon.tsx
  src/components/iconComponents/weather/weatherItem/SnowyIcon.tsx
  src/components/iconComponents/weather/weatherItem/SunnyIcon.tsx
  src/components/iconComponents/weather/weatherItem/ThunderStormIcon.tsx
  src/components/iconComponents/weather/weatherItem/WindyIcon.tsx
  src/types/IconPropsType.ts
Labels: 컴포넌트, 스타일

#28 Style: 기분에 해당하는 Icon 컴포넌트 작업과 기분 Icon 컴포넌트를 일렬로 정렬한 MoodList 컴포넌트 퍼블리싱 작업 완료
  src/components/iconComponents/mood/MoodList.stories.tsx
  src/components/iconComponents/mood/MoodList.tsx
  src/components/iconComponents/mood/moodItem/AngryIcon.tsx
  src/components/iconComponents/mood/moodItem/ExcitedIcon.tsx
  src/components/iconComponents/mood/moodItem/HappyIcon.tsx
  src/components/iconComponents/mood/moodItem/MediocreIcon.tsx
  src/components/iconComponents/mood/moodItem/SadIcon.tsx
  src/components/iconComponents/mood/moodItem/SmileIcon.tsx
  src/components/iconComponents/weather/WeatherList.stories.tsx
Labels: 컴포넌트, 스타일

#31 style: 로그인 페이지 퍼블리싱 작업 완료
  src/pages/LoginPage/page/index.tsx
Labels: 페이지, 스타일

#33 Style: ErrorPage 퍼블리싱 작업 완료
  src/components/header/DefaultHeader.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/header/HeaderWithProfile.tsx
  src/components/modals/EmptyImage.tsx
  src/pages/ErrorPage/components/GoHomeButton.tsx
  src/pages/ErrorPage/page/index.tsx
Labels: 페이지, 스타일, 핫픽스

#36 refactor: 작성되어있던 모든 컴포넌트에서의 font-[400] 스타일 속성 삭제
  src/components/buttons/BigButton.tsx
  src/components/buttons/ModalButton.tsx
  src/components/buttons/SmallButton.tsx
  src/components/buttons/ToggleButton.tsx
  src/components/header/DefaultHeader.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/header/HeaderWithProfile.tsx
  src/components/iconComponents/mood/MoodList.stories.tsx
  src/components/iconComponents/weather/WeatherList.stories.tsx
  src/components/modals/ChangeNameModal.tsx
  src/components/modals/DefaultModal.tsx
  src/components/modals/EmptyImage.tsx
  src/components/modals/ImageEditModal.tsx
  src/components/modals/ProfileModal.tsx
Labels: 스타일, 핫픽스

#38 Style: 메인 페이지(캘린더형, 목록형) 퍼블리싱 작업 완료
  package.json
  pnpm-lock.yaml
  src/components/buttons/Button.stories.tsx
  src/components/buttons/ToggleButton.tsx
  src/components/diary/DiaryItem.tsx
  src/components/diary/DiaryList.tsx
  src/components/header/DefaultHeader.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/header/HeaderWithProfile.tsx
  src/components/iconComponents/XIcon.tsx
  src/components/modals/ModalLayout.tsx
  src/components/modals/ProfileModal.tsx
  src/index.css
  src/pages/MainPage/components/DateManipulationBar.tsx
  src/pages/MainPage/components/calender/Calender.tsx
  src/pages/MainPage/components/calender/CalenderView.tsx
  src/pages/MainPage/page/index.tsx
  src/store/useToggleStore.ts
Labels: 페이지, 스타일, 핫픽스

#39 Style: 일기장 컴포넌트 퍼블리싱
  src/components/diary/Diary.stories.tsx
  src/components/diary/Diary.tsx
  src/components/diary/InputSection.tsx
  src/components/diary/TypingEffect.tsx
  src/components/diary/image/ImageCreationPanel.stories.tsx
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/diary/image/ImagesHistoryButton.tsx
  src/components/diary/list/DiaryItem.tsx
  src/components/diary/list/DiaryList.stories.tsx
  src/components/diary/list/DiaryList.tsx
  src/components/empty/EmptyState.tsx
  src/components/modals/ImageEditModal.tsx
  src/index.css
  src/pages/MainPage/components/calender/CalenderView.tsx
  src/store/CursorIndex.tsx
  tailwind.config.js
Labels: 컴포넌트, 기능, 스타일

#42 Style: 좋아요한 일기 페이지 퍼블리싱 작업 완료
  src/components/diary/list/DiaryItem.tsx
  src/components/diary/list/DiaryList.tsx
  src/pages/ErrorPage/page/index.tsx
  src/pages/LikedPage/components/NoLikedList.tsx
  src/pages/LikedPage/page/index.tsx
Labels: 페이지, 스타일

#44 Style: 검색 페이지 퍼블리싱 작업 완료
  src/App.tsx
  src/components/diary/list/DiaryItem.tsx
  src/components/diary/list/DiaryList.tsx
  src/components/iconComponents/LikeIcon.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchIcon.tsx
  src/components/search/SearchInput.tsx
  src/pages/SearchPage/page/index.tsx
Labels: fix, 컴포넌트, 페이지, 스타일

#46 Hotfix : Diary 컴포넌트의 InputSection 모눈종이 스타일을 textarea로 수정
  src/components/diary/Diary.tsx
  src/components/diary/InputSection.tsx
  src/components/diary/TypingEffect.tsx
  src/components/iconComponents/mood/MoodList.tsx
  src/components/iconComponents/weather/WeatherList.tsx
  src/store/CursorIndex.tsx
Labels: fix, 컴포넌트, 스타일

#48 Style : 일기 작성 / 수정 페이지 퍼블리싱 완료
  src/components/buttons/BigButton.tsx
  src/components/buttons/Button.stories.tsx
  src/components/diary/Diary.tsx
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/iconComponents/mood/MoodList.tsx
  src/components/iconComponents/weather/WeatherList.tsx
  src/components/modals/ImageEditModal.tsx
  src/pages/WriteDiaryPage/page/index.tsx
  src/store/diaryStore.ts
  src/store/imageStore.ts
Labels: 페이지, 스타일
