Repository DDrawry/ddrawry-FE, pull requests merged in 2024-11, with the labels that each got.

#76 Feat: 일기 페이지 api 연동
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/diary/useDiary.ts
  src/api/diary/useTempDiary.ts
  src/api/fetcher.ts
  src/api/liked/useLikeStatus.ts
  src/components/diary/Diary.tsx
  src/components/diary/DisplaySection.tsx
  src/components/diary/list/DiaryItem.tsx
  src/components/header/Header.stories.tsx
  src/components/header/HeaderWithLike.tsx
  src/components/iconComponents/LikeIcon.tsx
  src/pages/DiaryPage/components/DiaryButtonSection.tsx
  src/pages/DiaryPage/page/index.tsx
  src/pages/WriteDiaryPage/components/TempSaveModal.tsx
  src/pages/WriteDiaryPage/page/index.tsx
  src/store/diaryStore.ts
Labels: 페이지, 기능

#79 feat: 일기 수정 api 연동
  src/api/diary/useDiary.ts
  src/api/diary/useWriteDiary.ts
  src/pages/DiaryPage/components/DiaryButtonSection.tsx
  src/pages/WriteDiaryPage/components/WriteDiaryButtonSection.tsx
Labels: 페이지, 기능

#82 Hotfix: 좋아요페이지 오류 수정
  src/api/liked/useLikeStatus.ts
  src/api/liked/useLikedDiaries.ts
  src/components/diary/list/DiaryItem.tsx
  src/components/iconComponents/LikeIcon.tsx
  src/hooks/useDateControl.ts
  src/pages/LikedPage/page/index.tsx
  src/store/useDateStore.ts
Labels: 페이지, 핫픽스

#84 Feat: 프로필 모달 api 연동작업
  src/api/apiRoutes.ts
  src/api/users/useConfirmProfile.ts
  src/api/users/useDeleteAccount.ts
  src/api/users/useLogout.ts
  src/assets/images/XIcon.png
  src/assets/images/information.png
  src/components/header/HeaderWithProfile.tsx
  src/components/modals/InformationModal.tsx
  src/components/modals/Modal.stories.tsx
  src/components/modals/ProfileModal.tsx
  src/pages/MainPage/page/index.tsx
Labels: fix, 기능

#85 Hotfix: 에러 수정
  src/App.tsx
  src/api/diary/useDeleteDiary.ts
  src/api/diary/useDiary.ts
  src/api/diary/useGetDiary.ts
  src/api/diary/useTempDiary.ts
  src/api/diary/useUpdateDiary.ts
  src/api/diary/useWriteDiary.ts
  src/api/fetcher.ts
  src/api/tempDiary/tempApis.ts
  src/api/tempDiary/useCancelTempDiary.ts
  src/api/tempDiary/useSaveTempDiary.ts
  src/constants/domain.ts
  src/pages/DiaryPage/components/DiaryButtonSection.tsx
  src/pages/DiaryPage/page/index.tsx
  src/pages/LoginPage/loginHandler/oauthHandler.tsx
  src/pages/WriteDiaryPage/components/TempSaveModal.tsx
  src/pages/WriteDiaryPage/components/WriteDiaryButtonSection.tsx
  src/pages/WriteDiaryPage/page/index.tsx
  src/routes/CommonRoute.tsx
  src/types/diaryTypes.ts
  src/types/tempTypes.ts
  vite.config.ts
Labels: 핫픽스

#87 Feat: 메인 페이지 api 연동작업
  src/api/apiRoutes.ts
  src/api/calender/useCalender.ts
  src/api/tempDiary/useCancelTempDiary.ts
  src/api/users/useChangeUserSetting.ts
  src/components/diary/list/DiaryItem.tsx
  src/components/diary/list/DiaryList.tsx
  src/pages/MainPage/components/calender/Calender.tsx
  src/pages/MainPage/components/calender/CalenderItem.tsx
  src/pages/MainPage/components/calender/CalenderView.tsx
  src/pages/MainPage/page/index.tsx
  src/types/diaryTypes.ts
Labels: fix, 컴포넌트, 페이지, 기능, 스타일

#88 Feat: 검색페이지 api 연결
  src/api/diary/useSearchDiary.ts
  src/components/diary/list/DiaryItem.tsx
  src/components/diary/list/DiaryList.tsx
  src/components/iconComponents/LikeIcon.tsx
  src/pages/LoginPage/loginHandler/oauthHandler.tsx
  src/pages/SearchPage/components/SearchDiaryView.tsx
  src/pages/SearchPage/page/index.tsx
Labels: 페이지, 기능

#93 Fix: 메인페이지 캘린더 데이터 받아오는 로직 수정
  src/api/calender/useCalender.ts
  src/pages/MainPage/components/calender/CalenderView.tsx
Labels: fix, 페이지, 기능

#94 Feat: 그림 관련 API 연동
  pnpm-lock.yaml
  src/api/image/useCreateImage.ts
  src/api/image/useDeleteImage.ts
  src/api/image/useGetImage.ts
  src/api/liked/useLikeStatus.ts
  src/components/diary/Diary.tsx
  src/components/diary/image/ImageCreationPanel.tsx
  src/components/iconComponents/CircleXIcon.tsx
  src/components/modals/ImageEditModal.tsx
  src/components/modals/Modal.stories.tsx
  src/pages/DiaryPage/components/DiaryButtonSection.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/WriteDiaryPage/components/WriteDiaryButtonSection.tsx
  src/pages/WriteDiaryPage/page/index.tsx
  src/store/imageStore.ts
  src/store/useTempDataStore.ts
  src/types/imageTypes.ts
  src/types/tempTypes.ts
Labels: 컴포넌트, 기능

#95 Fix: 토글 버튼 상태 변경 오류 수정
  README.md
  src/components/buttons/ToggleButton.tsx
Labels: fix

#98 Chore: 로컬서버 https로 windows, mac OS 환경에서 적용할 수 있도록 하는 설정 파일 추가 및 package.json에 명령어 추가
  README.md
  init-https.sh
  package.json
  pnpm-lock.yaml
Labels: 세팅

#100 HotFix: 메인페이지 목록형 다이어리 api 호출 로직 수정
  src/api/calender/useCalender.ts
  src/pages/MainPage/components/calender/CalenderView.tsx
Labels: 기능, 핫픽스

#104 Hotfix: 핫픽스들 수정
  src/App.tsx
  src/api/diary/useUpdateDiary.ts
  src/api/diary/useWriteDiary.ts
  src/api/fetcher.ts
  src/api/image/useCreateImage.ts
  src/api/image/useDeleteImage.ts
  src/api/image/useGetCount.ts
  src/api/users/useChangeNickname.ts
  src/components/diary/Diary.stories.tsx
  src/components/diary/Diary.tsx
  src/components/diary/image/ImageCreationPanel.tsx
  src/pages/MainPage/components/calender/CalenderItem.tsx
  src/pages/WriteDiaryPage/page/index.tsx
  src/routes/CommonRoute.tsx
  src/routes/ProtectedRoute.tsx
  src/store/useTempDataStore.ts
  src/types/WriteDiaryTypes.ts
  src/types/imageTypes.ts
  src/types/tempTypes.ts
  src/utils/ErrorBoundary.tsx
  src/utils/queryClient.ts
Labels: 기능, 핫픽스

#106 Feat: 링크로 공유하기 기능 구현 및 공유된 페이지 퍼블리싱 작업
  package-lock.json
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/diary/useGetDiary.ts
  src/api/diary/useGetShareDiary.ts
  src/components/diary/Diary.tsx
  src/pages/DiaryPage/components/DiaryButtonSection.tsx
  src/pages/DiaryPage/page/index.tsx
  src/pages/SharedPage/index.tsx
  src/types/diaryTypes.ts
Labels: 페이지, 기능, 스타일
